# Generated by Django 5.2.4 on 2025-07-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects',
        ),
    ]
