# Generated by Django 5.2.4 on 2025-07-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_teacherprofile_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='edu_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='year_of_experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
