# Generated by Django 5.2.4 on 2025-07-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_teacherprofile_address_teacherprofile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
