# Generated by Django 5.2.4 on 2025-07-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_grade_student_grade_section_student_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
    ]
