# Generated by Django 5.2.4 on 2025-07-07 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='school.grade'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.grade'),
        ),
    ]
