# Generated by Django 5.2.4 on 2025-07-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_teacherprofile_is_profile_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='is_profile_complete',
        ),
    ]
