# Generated by Django 5.2.4 on 2025-07-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_section_grade_student_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('grade', 'name')},
        ),
    ]
