# Generated by Django 5.2.4 on 2025-07-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_section_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
