# Generated by Django 5.2.4 on 2025-07-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_grade_grade_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
