# Generated by Django 5.2.4 on 2025-07-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_section_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='capacity',
        ),
    ]
