# Generated by Django 5.2.4 on 2025-07-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_remove_section_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
