# Generated by Django 5.2.4 on 2025-07-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_grade_name'),
        ('users', '0002_customuser_is_school_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('school', 'name', 'grade_number')},
        ),
    ]
