# Generated by Django 5.2.4 on 2025-07-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_student_roll_number_alter_grade_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
