# Generated by Django 5.2.4 on 2025-07-09 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_teacherprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='sections',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.grade'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.section'),
        ),
    ]
