# Generated by Django 5.2.1 on 2025-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_assignment_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
