# Generated by Django 5.2.4 on 2025-07-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_remove_teacherprofile_grades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
