# Generated by Django 5.2.4 on 2025-07-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school.grade'),
        ),
    ]
